plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
    id 'kotlin-kapt'
    id 'com.google.gms.google-services'
    id 'com.google.firebase.crashlytics'
    id 'com.google.dagger.hilt.android'
}

def keystorePropertiesFile = rootProject.file("keystore.properties")
def keystoreProperties = new Properties()
keystoreProperties.load(new FileInputStream(keystorePropertiesFile))

android {
    namespace 'com.ls.entertainment.securitylocker'
    compileSdk 33

    signingConfigs {
        debug {
            keyAlias keystoreProperties['keyAlias']
            keyPassword keystoreProperties['keyPassword']
            storeFile file(keystoreProperties['storeFile'])
            storePassword keystoreProperties['storePassword']
        }
        release {
            keyAlias keystoreProperties['keyAlias_r']
            keyPassword keystoreProperties['keyPassword_r']
            storeFile file(keystoreProperties['storeFile_r'])
            storePassword keystoreProperties['storePassword_r']
        }
    }

    defaultConfig {
        applicationId "com.ls.entertainment.securitylocker"
        minSdk 21
        targetSdk 33
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            signingConfig signingConfigs.release
        }

        debug {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
            signingConfig signingConfigs.debug
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    kotlinOptions {
        jvmTarget = '1.8'
    }

    buildFeatures{
        dataBinding = true
        viewBinding = true
    }
}

kapt {
    correctErrorTypes true
}

dependencies {

    implementation 'androidx.core:core-ktx:1.7.0'
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'com.google.android.material:material:1.8.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test.ext:junit:1.1.5'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.5.1'

    implementation project(':base')

    // Kotlin
    implementation("androidx.navigation:navigation-fragment-ktx:2.5.1")
    implementation("androidx.navigation:navigation-ui-ktx:2.5.1")

    //appcompat
    implementation libraries.appcompat
    implementation libraries.fragment

    //kotlin
    implementation libraries.kotlin

    //view
    implementation libraries.material
    implementation libraries.constraintlayout

    implementation libraries.gson

    // rx android
    implementation libraries.rxandroid
    implementation libraries.rxjava
    implementation libraries.rxjava2

    //logger
    implementation libraries.timber

//    //ViewModel
    implementation libraries.viewmodel
    implementation libraries.lifecycleExt
    kapt libraries.liveData

    // Loading Image
    implementation libraries.glide
    kapt libraries.glideCompiler


    //google admod
    implementation 'com.google.android.gms:play-services-ads:22.0.0'

    def lifecycle_version = "2.0.0"
    implementation "androidx.lifecycle:lifecycle-extensions:$lifecycle_version"
    implementation "androidx.lifecycle:lifecycle-runtime:$lifecycle_version"
    annotationProcessor "androidx.lifecycle:lifecycle-compiler:$lifecycle_version"

    // lottie animation
    implementation 'com.airbnb.android:lottie:5.0.3'

    implementation platform('com.google.firebase:firebase-bom:31.0.2')
    implementation 'com.google.firebase:firebase-config-ktx'


    // Declare the dependencies for the Crashlytics and Analytics libraries
    // When using the BoM, you don't specify versions in Firebase library dependencies
    implementation 'com.google.firebase:firebase-crashlytics-ktx'
    implementation 'com.google.firebase:firebase-analytics-ktx'

    //work
    implementation "androidx.work:work-runtime-ktx:$work_version"
    androidTestImplementation "androidx.work:work-testing:$work_version"
    implementation "androidx.hilt:hilt-work:$hilt_jetpack_version"

    implementation("org.greenrobot:eventbus:3.3.1")

    implementation "com.google.dagger:hilt-android:2.44"
    kapt "com.google.dagger:hilt-compiler:2.44"

    // pdf viewer
    implementation 'com.github.barteksc:android-pdf-viewer:2.8.2'

    // room
    implementation "androidx.room:room-runtime:2.4.3"
    kapt "androidx.room:room-compiler:2.4.3"

    implementation("androidx.room:room-ktx:2.4.3")

    implementation 'com.andrognito.patternlockview:patternlockview:1.0.0'

    implementation 'com.github.kittinunf.fuel:fuel:2.1.0'
    implementation 'com.github.kittinunf.fuel:fuel-android:2.1.0'

    implementation 'com.andrognito.pinlockview:pinlockview:2.1.0'
    implementation 'me.itangqi.waveloadingview:library:0.3.5'

    // crop image library
    implementation 'com.github.yalantis:ucrop:2.2.7'
}